// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // RDK 首页 + 7 章显式 category（带 generated-index slug）包 autogen。
  // 10_Release_Note 不入侧边栏（版本发布并入首页末节，各版本页由 RDK.md 链接访问，不单独成章）。
  tutorialSidebar: [
    'RDK',
    { type: 'category', label: '快速开始', link: { type: 'generated-index', slug: '/Quick_start' }, items: [{ type: 'autogenerated', dirName: '01_Quick_start' }] },
    { type: 'category', label: '2. 系统配置', link: { type: 'generated-index', slug: '/System_configuration' }, items: [{ type: 'autogenerated', dirName: '02_System_configuration' }] },
    { type: 'category', label: '3. 开发示例', link: { type: 'generated-index', slug: '/Demos' }, items: [{ type: 'autogenerated', dirName: '03_Demos' }] },
    { type: 'category', label: '4. 简易 API', link: { type: 'generated-index', slug: '/Simple_API' }, items: [{ type: 'autogenerated', dirName: '04_Simple_API' }] },
    { type: 'category', label: '5. 进阶开发', link: { type: 'generated-index', slug: '/Advanced_development' }, items: [{ type: 'autogenerated', dirName: '07_Advanced_development' }] },
    { type: 'category', label: '6. 常见问题', link: { type: 'generated-index', slug: '/FAQ' }, items: [{ type: 'autogenerated', dirName: '08_FAQ' }] },
    { type: 'category', label: '7. 附录', link: { type: 'generated-index', slug: '/Appendix' }, items: [{ type: 'autogenerated', dirName: '09_Appendix' }] },
  ],
};

export default sidebars;
